version: '3.8'
services:
  rtsp-server:
    image: bluenviron/mediamtx
    container_name: rtmp-server
    ports:
      - '8554:8554'
      - '1935:1935'
    restart: unless-stopped

  ffmpeg-stream1:
    image: jrottenberg/ffmpeg
    container_name: ffmpeg-stream1
    command: '-re -stream_loop -1 -i /videos/NguyenOanh-PhanVanTri-01.mp4 -c:v libx264 -preset ultrafast -f flv rtmp://rtmp-server:1935/app/stream1'
    volumes:
      - ./video_streaming/videos/NguyenOanh-PhanVanTri-01.mp4:/videos/NguyenOanh-PhanVanTri-01.mp4:ro
    depends_on:
      - rtsp-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

  ffmpeg-stream2:
    image: jrottenberg/ffmpeg
    container_name: ffmpeg-stream2
    command: '-re -stream_loop -1 -i /videos/NguyenOanh-PhanVanTri-02.mp4 -c:v libx264 -preset ultrafast -f flv rtmp://rtmp-server:1935/app/stream2'
    volumes:
      - ./video_streaming/videos/NguyenOanh-PhanVanTri-02.mp4:/videos/NguyenOanh-PhanVanTri-02.mp4:ro
    depends_on:
      - rtsp-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
